name       : perl-lwp-mediatypes
version    : '6.04'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-MediaTypes-6.04.tar.gz : 8f1bca12dab16a1c2a7c03a49c5e58cce41a6fec9519f0aadfba8dad997919d9
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : LWP::MediaTypes - guess media type for a file or a URL
description: |
    This module provides functions for handling media (also known as MIME) types and encodings. The mapping from file extensions to media types is defined by the media.types file. If the ~/.media.types file exists it is used instead. For backwards compatibility we will also look for ~/.mime.types.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
