name       : perl-lwp-mediatypes
version    : 6.02
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GAAS/LWP-MediaTypes-6.02.tar.gz : 18790b0cc5f0a51468495c3847b16738f785a2d460403595001e0b932e5db676
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : LWP::MediaTypes - guess media type for a file or a URL
description: |
    This module provides functions for handling media (also known as MIME) types and encodings. The mapping from file extensions to media types is defined by the media.types file. If the ~/.media.types file exists it is used instead. For backwards compatibility we will also look for ~/.mime.types.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
